### ISSUE TITLE
Implement a database for the backend

### ISSUE THREAD

**Issue by bradenn** [ChicoState/Wild-Life#11]
While we won't immediately need a database to run the program, it may be useful in the future.

The following steps should occur:

1. Decide on a database paradigm (sql-like, noSQL, etc)
2. Pick a database (Postgres, mySQL, CassandraDB, MariaDB, mongoDB, documentDB, etc)
3. Implement in go
4. Decide how to pass credentials to the database
5. Create a wiki page documenting how someone can set up the database, and how to connect go to it on their computer.

**Comment by Qinbeans** [comment]
https://github.com/ChicoState/Wild-Life/wiki/Database
