### ISSUE TITLE
As a user I would like to be able to identify plants

### ISSUE THREAD

**Issue by Qinbeans** [ChicoState/Wild-Life#21]
Install GoCV and document installation.
- Install GoCV
- Document installation and usage in wiki

**Comment by Qinbeans** [comment]
Similar to #27-work together

**Comment by thsmale** [comment]
https://gocv.io/getting-started/

**Comment by thsmale** [comment]
Potential Models

- Support Vector Machines (SVM), Convolutional Neural Networks (CNN)  

- Pre-trained models:  VGG-16, Inception, ResNet50, EfficientNet
