### ISSUE TITLE
As a user I would like an AI to help me

### ISSUE THREAD

**Issue by Qinbeans** [ChicoState/Wild-Life#25]
Everyone should look for datasets

**Comment by thsmale** [comment]
Some datasets: 
https://www.quantitative-plant.org/dataset: Tons of images about cash crops 
https://www.imageclef.org/lifeclef/2016/plant 
https://www.usanpn.org/data/observational 
https://eol.org

**Comment by thsmale** [comment]
https://drive.google.com/drive/folders/1sc7TRIzpkq2mR_kJbpv-f1LPNSimuM9M?usp=sharing

**Comment by thsmale** [comment]
ImageNET
CIFAR
MNIST

**Comment by decoles** [comment]
https://drive.google.com/file/d/17_RELq4m1lWNozH_C_PoTYxaZ08bo9yn/view?usp=sharing around 500 picture data set of different searches for poison oak
